#Makefile
timeEvolutionTest: timeEvolutionTest.cpp vectorWrapper.hpp RBM.hpp defaultTraits.hpp getDataVector.hpp
	clang++ -std=c++11 timeEvolutionTest.cpp vectorWrapper.hpp RBM.hpp defaultTraits.hpp getDataVector.hpp
